version: "3.2"
services:
  mysql:
    container_name: mysql-didyn
    build:
      context: ./mysql/
    image: mysql:didyn
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=ddpwd
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/db:/var/lib/mysql
      - ./mysql/data/scripts:/scripts
  node:
    container_name: node-didyn
    build:
      context: ./node/
    image: node:didyn
    command: npm start
    networks:
      - frontend
      - backend
    links:
      - mysql
    volumes:
      - ./node/src:/home/node/app
    ports:
      - "9001:9001"
    depends_on:
      - mysql
    restart: always
  php:
    container_name: php-didyn
    build:
      context: ./php/
    image: php:didyn
    links:
      - node
    networks:
      - frontend
    volumes:
      - ./php/www:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - node
networks:
  frontend:
  backend: