SettingsGallery As CanvasComponent:
    AddItems: =true
    AddText: =txtSettingsAddItem.Text
    AddUser: =false
    ColorCritical: =RGBA(215,0,16,1)
    ColorSelected: =RGBA(215,0,16,1)
    EmailDomain: ="@vetta.digital"
    Fill: =RGBA(0, 0, 0, 0)
    Height: =663
    Items: |-
        =Table({Title: "AAA"})
    NoItemsText: ="Nenhum item encontrado"
    OnReset: =Reset(txtSettingsAddItem);Reset(txtSettingsSearchItem);Reset(cmbSettingsNewUser)
    SearchItems: =true
    SearchText: =txtSettingsSearchItem.Text
    SelectedItem: =galSettings.Selected
    Title: ="Clientes"
    UserSearchText: =cmbSettingsNewUser.SearchText
    UserSelectedMail: =cmbSettingsNewUser.Selected.Mail
    UsersItems: |-
        =Table({Mail: "bbb", value:"aaa"})
    Width: =1366
    X: =0
    Y: =0
    ZIndex: =4

    galSettings As gallery.galleryVertical:
        BorderColor: =RGBA(32, 54, 71, 1)
        BorderStyle: =BorderStyle.None
        Fill: =White
        Height: =551
        Items: =SettingsGallery.Items
        Layout: =Layout.Vertical
        OnSelect: =Set(varSettingsCurrentItem,ThisItem);Set(varSettingsConfirmDeletion,true)
        ShowNavigation: =true
        ShowScrollbar: =false
        TemplateSize: =81
        Width: =SettingsGallery.Width
        WrapCount: =4
        Y: =112
        ZIndex: =1

        btnSettingsItemSelection As button:
            BorderColor: =RGBA(0, 121, 187, 1)
            BorderStyle: =BorderStyle.None
            BorderThickness: =0
            Color: =Black
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledColor: =Self.Color
            DisabledFill: =Self.Fill
            Fill: =If(varSettingsConfirmDeletion && varSettingsCurrentItem.Title=ThisItem.Title,SettingsGallery.ColorSelected,White)
            FocusedBorderThickness: =0
            FontWeight: =FontWeight.Semibold
            Height: =lblSettingsItem.Height
            HoverFill: =ColorFade(Self.Fill, -5%)
            PressedColor: =Self.Color
            PressedFill: =ColorFade(Self.Fill, -10%)
            RadiusBottomLeft: =15
            RadiusBottomRight: =15
            RadiusTopLeft: =15
            RadiusTopRight: =15
            Size: =10
            Text: =""
            Width: =208
            X: =14
            Y: =lblSettingsItem.Y
            ZIndex: =1

        shpCircleSettingsDeleteItem As circle:
            BorderColor: =RGBA(32, 54, 71, 1)
            Fill: =SettingsGallery.ColorCritical
            Height: =30
            OnSelect: =Select(icoSettingsDeleteItem)
            Visible: =icoSettingsDeleteItem.Visible
            Width: =30
            X: =233
            Y: =lblSettingsItem.Y
            ZIndex: =2

        lblSettingsItem As label:
            Align: =Align.Center
            AutoHeight: =true
            BorderColor: =RGBA(32, 54, 71, 1)
            Color: =If(varSettingsConfirmDeletion && varSettingsCurrentItem.Title=ThisItem.Title,White,Black)
            DisabledColor: =RGBA(166, 166, 166, 1)
            Font: =Font.'Segoe UI'
            Height: =28
            OnSelect: =Select(Parent)
            Size: =11
            Text: =ThisItem.Title
            VerticalAlign: =Middle
            Width: =204
            X: =16
            Y: =8
            ZIndex: =3

        shpSettingsItemDivider As rectangle:
            BorderColor: =RGBA(32, 54, 71, 1)
            Fill: =RGBA(230, 230, 230, 1)
            Height: =0.5
            Width: =220
            X: =12
            Y: =77
            ZIndex: =4

        icoSettingsDeleteItem As icon.Trash:
            BorderColor: =RGBA(32, 54, 71, 1)
            Color: |
                =White
            DisabledBorderColor: =RGBA(166, 166, 166, 1)
            DisabledColor: =RGBA(244, 244, 244, 1)
            Fill: =Transparent
            Height: =22
            Icon: =Icon.Trash
            OnSelect: =Set(varActionSettingsDelete,true)
            Visible: =varSettingsConfirmDeletion && varSettingsCurrentItem.Title=ThisItem.Title
            Width: =22
            X: =237.5
            Y: =lblSettingsItem.Y+4
            ZIndex: =5

    lblSettingsMenuTitle As label:
        BorderColor: =RGBA(32, 54, 71, 1)
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =65
        Size: =18
        Text: =SettingsGallery.Title
        Width: =306
        X: =24
        ZIndex: =2

    txtSettingsSearchItem As text:
        BorderColor: =LightGray
        Clear: =true
        Color: =RGBA(0, 0, 0, 1)
        Default: =""
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        FocusedBorderThickness: =1
        Font: =Font.'Segoe UI'
        HintText: ="Buscar " & Lower(SettingsGallery.Title) & "..."
        HoverBorderColor: =Self.BorderColor
        HoverColor: =RGBA(0, 0, 0, 1)
        HoverFill: =LightGray
        PaddingLeft: =10
        PaddingRight: =45
        PressedBorderColor: =Self.BorderColor
        Reset: =true
        Size: =11
        Visible: =SettingsGallery.SearchItems && !SettingsGallery.AddUser
        Width: =328
        X: =24
        Y: =59
        ZIndex: =3

    icoSettingsSearchItem As icon.Search:
        BorderColor: =RGBA(32, 54, 71, 1)
        BorderStyle: =BorderStyle.None
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =25
        Icon: =Icon.Search
        Visible: =SettingsGallery.SearchItems && !SettingsGallery.AddUser && IsBlank(txtSettingsSearchItem.Text)
        Width: =25
        X: =319
        Y: =67
        ZIndex: =4

    txtSettingsAddItem As text:
        BorderColor: =LightGray
        Clear: =true
        Color: =RGBA(0, 0, 0, 1)
        Default: =""
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        FocusedBorderThickness: =1
        Font: =Font.'Segoe UI'
        HintText: ="Inserir um novo item..."
        HoverBorderColor: =Self.BorderColor
        HoverColor: =RGBA(0, 0, 0, 1)
        HoverFill: =LightGray
        PaddingLeft: =10
        PaddingRight: =45
        PressedBorderColor: =Self.BorderColor
        Reset: =true
        Size: =11
        Visible: =SettingsGallery.AddItems && !SettingsGallery.AddUser
        Width: =328
        X: =If(SettingsGallery.AddItems,If(SettingsGallery.SearchItems,386,24))
        Y: =59
        ZIndex: =5

    icoSettingsAddItem As icon.Add:
        BorderColor: =RGBA(32, 54, 71, 1)
        BorderStyle: =BorderStyle.None
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =Self.Color
        Height: =26
        HoverColor: =Self.Color
        Icon: =Icon.Add
        OnSelect: =Set(varActionSettingsAddItem,true)
        PressedColor: =Self.Color
        Visible: =SettingsGallery.AddItems && !SettingsGallery.AddUser
        Width: =26
        X: =txtSettingsAddItem.X+txtSettingsAddItem.Width+8
        Y: =66
        ZIndex: =6

    shpBarDivider As rectangle:
        BorderColor: =RGBA(32, 54, 71, 1)
        Fill: =RGBA(230, 230, 230, 1)
        Height: =50
        Visible: =SettingsGallery.SearchItems && SettingsGallery.AddItems && !SettingsGallery.AddUser
        Width: =1
        X: =369
        Y: =54
        ZIndex: =7

    cmbSettingsNewUser As combobox:
        BorderColor: =RGBA(230, 230, 230, 1)
        BorderThickness: =1
        ChevronBackground: =White
        ChevronDisabledBackground: =Self.ChevronBackground
        ChevronDisabledFill: =Self.ChevronFill
        ChevronFill: =Black
        ChevronHoverBackground: =Self.ChevronBackground
        DefaultSelectedItems: =Blank()
        DisabledBorderColor: =Self.BorderColor
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =Self.Fill
        DisplayFields: =["Mail"]
        FocusedBorderThickness: =1
        Font: =Font.'Segoe UI'
        HoverBorderColor: =Self.BorderColor
        HoverColor: =RGBA(0, 0, 0, 1)
        HoverFill: =LightGray
        InputTextPlaceholder: ="Insira o e-mail do usuário"
        Items: =SettingsGallery.UsersItems
        PaddingLeft: =10
        PressedBorderColor: =Self.BorderColor
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =Black
        Reset: =true
        SearchFields: =["Mail"]
        SearchItems: =Search(SettingsGallery.UsersItems,cmbSettingsNewUser.SearchText,"Mail")
        SelectionFill: =Black
        SelectionTagColor: =Black
        SelectionTagFill: =LightGray
        SelectMultiple: =false
        Visible: =!SettingsGallery.AddItems && SettingsGallery.AddUser
        X: =If(SettingsGallery.AddUser,24,386)
        Y: =59
        ZIndex: =8

    icoSettingsAddUser As icon.Add:
        BorderColor: =RGBA(32, 54, 71, 1)
        BorderStyle: =BorderStyle.None
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =Self.Color
        Height: =26
        HoverColor: =Self.Color
        Icon: =Icon.AddUser
        OnSelect: =Set(varActionSettingsAddUser,true)
        PressedColor: =Self.Color
        Visible: =!SettingsGallery.AddItems && SettingsGallery.AddUser
        Width: =26
        X: =cmbSettingsNewUser.X+cmbSettingsNewUser.Width+15
        Y: =68
        ZIndex: =9

    lblNoItems_1 As label:
        Align: =Align.Center
        BorderColor: =RGBA(0, 18, 107, 1)
        Color: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Font: =Font.'Segoe UI'
        Height: =50
        Size: =13
        Text: =SettingsGallery.NoItemsText
        Visible: =CountRows(galSettings.AllItems)=0
        Width: =galSettings.Width
        Y: =334
        ZIndex: =10

