"'Screen Settings' As screen":
    LoadingSpinnerColor: =RGBA(100, 118, 132, 1)
    OnVisible: |
        =Set(varActionConfirmDelete,false);
        Set(varDeleteItem,false);
        Set(varExpandedMenu,false);
        Set(varAppBarAction,0);
        Set(varActionSettingsAddItem,false);
        Set(varActionSettingsAddUser,false);
        Set(varActionSettingsDelete,false);
        Set(varPermissionsSettings,1);
        Set(varActionSettingsPermissionsAddUser,false);
        Set(varActionSettingsPermissionsDelete,false);
        Set(varActionLateralBar,false);
        
        Concurrent(
            Refresh('[DPE_001] Clientes');ClearCollect(colClientes,'[DPE_001] Clientes'),
            Refresh('[DPE_001] Cargos');ClearCollect(colCargos,'[DPE_001] Cargos'),
            Refresh('[DPE_001] Centros de Custo');ClearCollect(colCentrosdeCusto,'[DPE_001] Centros de Custo'),
            Refresh('[DPE_001] Gestores');ClearCollect(colGestores,'[DPE_001] Gestores'),
            Refresh('[DPE_001] Tipos de Treinamento');ClearCollect(colTiposTreinamento,'[DPE_001] Tipos de Treinamento'),
            Refresh('[DPE_001] Permissões');ClearCollect(colPermissoes,'[DPE_001] Permissões')
        );

    tmrSettingsAppBarAction As timer:
        Duration: =1
        Fill: =RGBA(56, 96, 178, 1)
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
        OnTimerEnd: |-
            =Switch(
                varAppBarAction,
                1,
                    Concurrent(
                        Refresh('[DPE_001] Clientes');ClearCollect(colClientes,'[DPE_001] Clientes'),
                        Refresh('[DPE_001] Cargos');ClearCollect(colCargos,'[DPE_001] Cargos'),
                        Refresh('[DPE_001] Centros de Custo');ClearCollect(colCentrosdeCusto,'[DPE_001] Centros de Custo'),
                        Refresh('[DPE_001] Gestores');ClearCollect(colGestores,'[DPE_001] Gestores'),
                        Refresh('[DPE_001] Tipos de Treinamento');ClearCollect(colTiposTreinamento,'[DPE_001] Tipos de Treinamento'),
                        Refresh('[DPE_001] Permissões');ClearCollect(colPermissoes,'[DPE_001] Permissões')
                    );
            
                    Notify("Dados atualizados com sucesso!",Success),
                2,
                    Navigate('Screen Home')
            );
            
            Set(varAppBarAction,0);
        Reset: =varAppBarAction=0 || App.ActiveScreen.Name<>"Screen Settings"
        Start: =varAppBarAction<>0 && App.ActiveScreen.Name="Screen Settings"
        Visible: =false
        X: =55
        Y: =728
        ZIndex: =1

    tmrActionsSettingsGalleryDelete As timer:
        Duration: =1
        Fill: =RGBA(56, 96, 178, 1)
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
        OnTimerEnd: |
            =If(
                SettingsGallery_1.Visible,
                    Concurrent(
                        Remove(colClientes,LookUp(colClientes,Title=SettingsGallery_1.SelectedItem.Title)),
                        Remove('[DPE_001] Clientes',LookUp('[DPE_001] Clientes',Title=SettingsGallery_1.SelectedItem.Title))
                    );
                    Reset(SettingsGallery_1),
            
                SettingsGallery_2.Visible,
                    Concurrent(
                        Remove(colCargos,LookUp(colCargos,Title=SettingsGallery_2.SelectedItem.Title)),
                        Remove('[DPE_001] Cargos',LookUp('[DPE_001] Cargos',Title=SettingsGallery_2.SelectedItem.Title))
                    );
                    Reset(SettingsGallery_2),
            
                SettingsGallery_3.Visible,
                    Concurrent(
                        Remove(colCentrosdeCusto,LookUp(colCentrosdeCusto,Title=SettingsGallery_3.SelectedItem.Title)),
                        Remove('[DPE_001] Centros de Custo',LookUp('[DPE_001] Centros de Custo',Title=SettingsGallery_3.SelectedItem.Title))
                    );
                    Reset(SettingsGallery_3),
            
                SettingsGallery_4.Visible,
                    Concurrent(
                        Remove(colGestores,LookUp(colGestores,Title=SettingsGallery_4.SelectedItem.Title)),
                        Remove('[DPE_001] Gestores',LookUp('[DPE_001] Gestores',Title=SettingsGallery_4.SelectedItem.Title))
                    );
                    Reset(SettingsGallery_4),
            
                SettingsGallery_5.Visible,
                    Concurrent(
                        Remove(colTiposTreinamento,LookUp(colTiposTreinamento,Title=SettingsGallery_5.SelectedItem.Title)),
                        Remove('[DPE_001] Tipos de Treinamento',LookUp('[DPE_001] Tipos de Treinamento',Title=SettingsGallery_5.SelectedItem.Title))
                    );
                    Reset(SettingsGallery_5)
            );
            
            Set(varActionSettingsDelete,false);
            
            Notify("Item deletado com sucesso!",Success);
        Reset: =varActionSettingsDelete=false
        Start: =varActionSettingsDelete=true
        Visible: =false
        X: =221
        Y: =728
        ZIndex: =2

    tmrActionsSettingsGalleryAdd As timer:
        Duration: =1
        Fill: =RGBA(56, 96, 178, 1)
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
        OnTimerEnd: |
            =If(SettingsGallery_1.Visible,
                    Concurrent(
                        Patch(colClientes,Defaults(colClientes),{
                            Title: SettingsGallery_1.AddText}
                        ),
                        Patch('[DPE_001] Clientes',Defaults('[DPE_001] Clientes'),{
                            Title: SettingsGallery_1.AddText}
                        )
                    ); 
                    Reset(SettingsGallery_1),
            
                SettingsGallery_2.Visible,
                    Concurrent(
                        Patch(colCargos,Defaults(colCargos),{
                            Title: SettingsGallery_2.AddText}
                        ),
                        Patch('[DPE_001] Cargos',Defaults('[DPE_001] Cargos'),{
                            Title: SettingsGallery_2.AddText}
                        )
                    ); 
                    Reset(SettingsGallery_2),
            
                SettingsGallery_3.Visible,
                    Concurrent(
                        Patch(colCentrosdeCusto,Defaults(colCentrosdeCusto),{
                            Title: SettingsGallery_3.AddText}
                        ),
                        Patch('[DPE_001] Centros de Custo',Defaults('[DPE_001] Centros de Custo'),{
                            Title: SettingsGallery_3.AddText}
                        )
                    ); 
                    Reset(SettingsGallery_3),
            
                SettingsGallery_5.Visible,
                    Concurrent(
                        Patch(colTiposTreinamento,Defaults(colTiposTreinamento),{
                            Title: SettingsGallery_5.AddText}
                        ),
                        Patch('[DPE_001] Tipos de Treinamento',Defaults('[DPE_001] Tipos de Treinamento'),{
                            Title: SettingsGallery_5.AddText}
                        )
                    ); 
                    Reset(SettingsGallery_5)
            );
            
            Set(varActionSettingsAddItem,false);
            
            Notify("Item inserido com sucesso!",Success);
        Reset: =varActionSettingsAddItem=false
        Start: =varActionSettingsAddItem=true
        Visible: =false
        X: =381
        Y: =728
        ZIndex: =3

    tmrActionsSettingsGalleryAddUser As timer:
        Duration: =1
        Fill: =RGBA(56, 96, 178, 1)
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
        OnTimerEnd: |-
            =If(
                SettingsGallery_4.Visible,
                If(SettingsGallery_4.EmailDomain in Lower(SettingsGallery_4.UserSelectedMail),
                    If(IsBlank(LookUp(colGestores,Title=Lower(SettingsGallery_4.UserSelectedMail))),
                        Concurrent(
                            Patch(colGestores,Defaults(colGestores),{
                                Title: SettingsGallery_4.UserSelectedMail}
                            ),
                            Patch('[DPE_001] Gestores',Defaults('[DPE_001] Gestores'),{
                                Title: SettingsGallery_4.UserSelectedMail}
                            )
                        );
                        Notify("Usuário inserido com sucesso!",Success); 
                        Reset(SettingsGallery_4),
                        Notify("Este usuário já está adicionado à lista!",Error)
                    ),
                    Notify("Insira um email válido!",Error))
                );
            
            Set(varActionSettingsAddUser,false);
        Reset: =varActionSettingsAddUser=false
        Start: =varActionSettingsAddUser=true
        Visible: =false
        X: =522
        Y: =728
        ZIndex: =4

    tmrActionsPermissionsGalleryDelete As timer:
        Duration: =1
        Fill: =RGBA(56, 96, 178, 1)
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
        OnTimerEnd: |
            =If(PermissionsGallery_1.Visible,
                Remove('[DPE_001] Permissões',LookUp('[DPE_001] Permissões',Title=PermissionsGallery_1.SelectedItem.Title));
                ClearCollect(colPermissoes,'[DPE_001] Permissões')
            );
            
            Set(varActionSettingsPermissionsDelete,false);
            
            Notify("Usuário removido com sucesso!",Success);
        Reset: =varActionSettingsPermissionsDelete=false
        Start: =varActionSettingsPermissionsDelete=true
        Visible: =false
        X: =241
        Y: =728
        ZIndex: =5

    tmrActionsPermissionsGalleryAddUser As timer:
        Duration: =1
        Fill: =RGBA(56, 96, 178, 1)
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
        OnTimerEnd: |-
            =If(
                PermissionsGallery_1.Visible,
                If(PermissionsGallery_1.EmailDomain in Lower(PermissionsGallery_1.PermissionsUserSelectedMail),
                    If(
                            IsBlank(LookUp(colPermissoes, Lower(Switch(varPermissionsSettings,
                                1,Step1,
                                2,Step2,
                                3,Step3,
                                -2,Delete,
                                -1,Admin
                                )) = Lower(PermissionsGallery_1.PermissionsUserSelectedMail))
                            )
                        ,
                            Patch('[DPE_001] Permissões',Defaults('[DPE_001] Permissões'),
                                {
                                    Title: GUID(),
                                    Step1: If(varPermissionsSettings=1,PermissionsGallery_1.PermissionsUserSelectedMail,GUID()),
                                    Step2: If(varPermissionsSettings=2,PermissionsGallery_1.PermissionsUserSelectedMail,GUID()),
                                    Step3: If(varPermissionsSettings=3,PermissionsGallery_1.PermissionsUserSelectedMail,GUID()),
                                    Delete: If(varPermissionsSettings=-2,PermissionsGallery_1.PermissionsUserSelectedMail,GUID()),
                                    Admin: If(varPermissionsSettings=-1,PermissionsGallery_1.PermissionsUserSelectedMail,GUID())
                                }
                            );
                            ClearCollect(colPermissoes,'[DPE_001] Permissões');
                            
                            Reset(PermissionsGallery_1);
                            Notify("Permissão concedida com sucesso!",Success),
            
                            Notify("Este usuário já possui essa permissão!",Error)
                    ),
                    Notify("Você deve selecionar um e-mail válido!",Error)
                )
            
            );
            
            Set(varActionSettingsPermissionsAddUser,false);
        Reset: =varActionSettingsPermissionsAddUser=false
        Start: =varActionSettingsPermissionsAddUser=true
        Visible: =false
        X: =542
        Y: =728
        ZIndex: =6

    tmrLateralBarAction As timer:
        Duration: =1
        Fill: =RGBA(100, 118, 132, 1)
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(100, 118, 132, 1), -20%)
        OnTimerEnd: |-
            =Reset(SettingsGallery_1);Reset(SettingsGallery_2);Reset(SettingsGallery_3);
            Reset(SettingsGallery_4);Reset(SettingsGallery_5);Reset(PermissionsGallery_1);
            Set(varSettingsConfirmDeletion,false);
            
            Set(varActionLateralBar,false);
        Reset: =varActionLateralBar=false
        Start: =varActionLateralBar=true
        Visible: =false
        X: =452
        Y: =24
        ZIndex: =7

    LateralBar_2 As LateralBar:
        ExpandMenuWidth: =215
        Height: =663
        Icon2: =Icon.Globe
        Icon3: =Icon.ToolsWrench
        Icon4: =Icon.Money
        Icon5: =Icon.People
        Icon6: =Icon.Notebook
        Icon7: =Icon.Key
        Label1: =""
        Label2: ="Clientes"
        Label3: ="Cargos"
        Label4: ="Centros de Custo"
        Label5: ="Gestores"
        Label6: ="Tipo de Treinamento"
        Label7: ="Permissões"
        NumberIcons: =7
        ShowFilter: =false
        ShowMenuText: =true
        ThemeColor: =ColorSuccess.Color
        Y: =105
        ZIndex: =8

    AppBar_7 As AppBar:
        Action3: =false
        Action4: =false
        Icon2: =Icon.Home
        Logo: =vetta
        ShowButton: =false
        Title: ="Configurações"
        ZIndex: =9

    SettingsGallery_4 As SettingsGallery:
        AddItems: =false
        AddUser: =true
        ColorSelected: =ColorSuccess.Color
        Items: =SortByColumns(colGestores,"Title",Ascending)
        NoItemsText: ="Nenhum Gestor encontrado"
        SearchItems: =false
        Title: ="Gestores"
        UsersItems: |-
            =Filter(UsuáriosdoOffice365.SearchUserV2({searchTerm:SettingsGallery_4.UserSearchText}).value,SettingsGallery_4.EmailDomain in Mail)
        Visible: =varSelectedMenu=4
        Width: =If(varExpandedMenu,1366-LateralBar_2.ExpandMenuWidth,1366-LateralBar_2.CollapseMenuWidth)
        X: =If(!varExpandedMenu,LateralBar_2.CollapseMenuWidth,LateralBar_2.CollapseMenuWidth+LateralBar_2.ExpandMenuWidth-LateralBar_2.CollapseMenuWidth)
        Y: =105
        ZIndex: =10

    SettingsGallery_5 As SettingsGallery:
        ColorSelected: =ColorSuccess.Color
        Items: =SortByColumns(Filter(colTiposTreinamento,SettingsGallery_5.SearchText in Title),"Title",Ascending)
        NoItemsText: ="Nenhum Tipo de Treinamento encontrado"
        Title: ="Tipos de Treinamento"
        Visible: =varSelectedMenu=5
        Width: =If(varExpandedMenu,1366-LateralBar_2.ExpandMenuWidth,1366-LateralBar_2.CollapseMenuWidth)
        X: =If(!varExpandedMenu,LateralBar_2.CollapseMenuWidth,LateralBar_2.CollapseMenuWidth+LateralBar_2.ExpandMenuWidth-LateralBar_2.CollapseMenuWidth)
        Y: =105
        ZIndex: =11

    SettingsGallery_1 As SettingsGallery:
        ColorSelected: =ColorSuccess.Color
        Items: =SortByColumns(Filter(colClientes,SettingsGallery_1.SearchText in Title),"Title",Ascending)
        NoItemsText: ="Nenhum Cliente encontrado"
        Visible: =varSelectedMenu=1
        Width: =If(varExpandedMenu,1366-LateralBar_2.ExpandMenuWidth,1366-LateralBar_2.CollapseMenuWidth)
        X: =If(!varExpandedMenu,LateralBar_2.CollapseMenuWidth,LateralBar_2.CollapseMenuWidth+LateralBar_2.ExpandMenuWidth-LateralBar_2.CollapseMenuWidth)
        Y: =105
        ZIndex: =13

    SettingsGallery_2 As SettingsGallery:
        ColorSelected: =ColorSuccess.Color
        Items: =SortByColumns(Filter(colCargos,SettingsGallery_2.SearchText in Title),"Title",Ascending)
        NoItemsText: ="Nenhum Cargo encontrado"
        Title: ="Cargos"
        Visible: =varSelectedMenu=2
        Width: =If(varExpandedMenu,1366-LateralBar_2.ExpandMenuWidth,1366-LateralBar_2.CollapseMenuWidth)
        X: =If(!varExpandedMenu,LateralBar_2.CollapseMenuWidth,LateralBar_2.CollapseMenuWidth+LateralBar_2.ExpandMenuWidth-LateralBar_2.CollapseMenuWidth)
        Y: =105
        ZIndex: =14

    SettingsGallery_3 As SettingsGallery:
        ColorSelected: =ColorSuccess.Color
        Items: =SortByColumns(Filter(colCentrosdeCusto,SettingsGallery_3.SearchText in Title),"Title",Ascending)
        NoItemsText: ="Nenhum Centro de Custo encontrado"
        Title: ="Centros de Custo"
        Visible: =varSelectedMenu=3
        Width: =If(varExpandedMenu,1366-LateralBar_2.ExpandMenuWidth,1366-LateralBar_2.CollapseMenuWidth)
        X: =If(!varExpandedMenu,LateralBar_2.CollapseMenuWidth,LateralBar_2.CollapseMenuWidth+LateralBar_2.ExpandMenuWidth-LateralBar_2.CollapseMenuWidth)
        Y: =105
        ZIndex: =15

    PermissionsGallery_1 As PermissionsGallery:
        ColorSelected: =ColorSuccess.Color
        Items: |-
            =Filter(colPermissoes,PermissionsGallery_1.EmailDomain in Switch(varPermissionsSettings,
                -1,Admin,
                -2,Delete,
                1,'Step 1',
                2,'Step 2',
                3,'Step 3'
            ))
        Label1: ="RH"
        Label2: ="DP"
        Label3: ="CCI"
        NumberPermissions: =3
        UsersItems: |-
            =Filter(UsuáriosdoOffice365.SearchUserV2({searchTerm:PermissionsGallery_1.PermissionUserSearchText}).value,PermissionsGallery_1.EmailDomain in Mail)
        Visible: =varSelectedMenu=6
        Width: =If(varExpandedMenu,1366-LateralBar_2.ExpandMenuWidth,1366-LateralBar_2.CollapseMenuWidth)
        X: =If(!varExpandedMenu,LateralBar_2.CollapseMenuWidth,LateralBar_2.CollapseMenuWidth+LateralBar_2.ExpandMenuWidth-LateralBar_2.CollapseMenuWidth)
        Y: =105
        ZIndex: =16

